### ISSUE TITLE
请问能否提供2019年遥感图像稀疏表征与智能分析竞赛中的变化检测数据集，谢谢

### ISSUE THREAD

**Issue by neverstoplearn** [CarryHJR/remote-sense-quickstart#4]

**Comment by CarryHJR** [comment]
留邮件私发

**Comment by zhengxinvip** [comment]
> 留邮件私发

2018202130034@whu.edu.cn 前段时间时间出差太忙  抱歉了  这是我的邮箱 期待你的邮件  非常感谢

**Comment by lsh1994** [comment]
2557033248@qq.com，麻烦作者也发我一份变化检测数据集

**Comment by Fanz2019** [comment]
513572289@qq.com，能不能给我也发一份变化检测数据集，非常感谢

**Comment by Sean-Whale** [comment]
tianji07@126.com，请问作者可不可以也分享一份2019年预测图像稀疏表征与智能分析竞赛中的变化检测数据集

**Comment by yonglinZ** [comment]
243545835@qq.com,求变化检测数据集，谢谢作者。

**Comment by CarryHJR** [comment]
不私发了，统一放这了，链接失效了再给我发邮件 carryhjr@gmail.com

链接: https://pan.baidu.com/s/1zt8KHwtuVFkXSoJTB53ryA 提取码: rw4f
